version: '3.5'

services:
    postgres:
        container_name: postgres_container
        image: postgres
        environment:
            POSTGRES_USER: ${DB_USERNAME:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
            PGDATA: /data/postgres
        volumes:
            - postgres:/database/postgres
            - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

        ports:
            - "5432:5432"
        networks:
            - postgres
        restart: unless-stopped

networks:
    postgres:
        driver: bridge

volumes:
    postgres:
